version: '3'

services:
  web:
    platform: linux/amd64 # M1 Mac Support
    build: .
    ports:
      - '8888:8888'
      
    # mount先指定
    volumes:
      - '.:/work'

    # -it command
    tty: true # -t
    stdin_open: true # -i
