version: '3'

services:
  mariadb:
    image: "mariadb:${TAG}"
    container_name: "mariadb${TAG}"
    env_file: .env
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "${DATABASE}"
      MYSQL_ROOT_USER: "${MYSQL_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true

  web:
    platform: linux/amd64 # M1 Mac Support
    build: .
    ports:
      - '8888:8888'
      
    # mount先指定
    volumes:
      - '.:/work'

    # -it command
    tty: true # -t
    stdin_open: true # -i

    depends_on:
      - mariadb
    links:
      - mariadb

volumes:
  db-data:
