version: '3'

services:
  web:
    build: .
    ports:
      - '8888:8888'
    # TODO: M1用に使用したいが。。。
    # platform: linux/amd64
      
    # mount先指定
    volumes:
      - '.:/work'

    # -it command
    tty: true # -t
    stdin_open: true # -i
